esphome:
  name: heatingpump
  friendly_name: "WP"

  platform: ESP32
  board: esp32dev

# Enable logging
logger:
  level: INFO

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key  

ota:
  platform: esphome
  password: !secret ota_password    

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.178.194
    gateway: 192.168.178.1
    dns1: 192.168.178.25
    subnet: 255.255.255.0
  use_address: heatingpump.local 

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Heatingpump Fallback Hotspot"
    password: "AsBl9n46jlOx"  
  
time:
  - platform: homeassistant
    id: homeassistant_time

substitutions:
  interval_very_fast: 15s
  interval_fast: 30s
  interval_medium: 60s
  interval_slow: 5min
  interval_very_slow: 15min
  interval_once_in_a_while: 1h

  #ggf. Einblenden.
  entity_room_temperature: "sensor.durchschnittstemperatur"
  # entity_room_temperature: "sensor.durchschnittstemperatur_haus_ohne_keller  
  entity_humidity: "sensor.durchschnitt_luftfeuchtigkeit_haus"

#########################################
#                                       #
#   SPI Konfiguration                   #
#                                       #
#########################################
spi:
  id: McpSpi
  clk_pin: GPIO26
  mosi_pin: GPIO27
  miso_pin: GPIO14  


#########################################
#                                       #
#   canbus Konfiguration                #
#                                       #
#########################################
canbus:
  - platform: mcp2515
    id: my_mcp2515
    spi_id: McpSpi
    cs_pin: GPIO12
    can_id: 700
    use_extended_id: false
    bit_rate: 20kbps
    on_frame:  

#########################################
#                                       #
#   Buttons                             #
#                                       #
#########################################
button:
  - platform: restart
    name: "Restart ESP32-WP25AC"


#########################################
#                                       #
#   Packages                            #
#                                       #
#########################################
packages:
#  sensors: !include OneESP32ToRuleWP25AC/yaml/sensors.yaml
  wp25ac: !include OneESP32ToRuleWP25AC/yaml/wp25ac.yaml
# thz404: !include OneESP32ToRuleWP25AC/yaml/thz404.yaml
# thz504: !include OneESP32ToRuleWP25AC/yaml/thz504.yaml
# thz55eco: !include OneESP32ToRuleWP25AC/yaml/thz5_5_eco.yaml
# ttf07: !include OneESP32ToRuleWP25AC/yaml/ttf07.yaml    
