################################################################################
#                                                                              #
#  ESPHome Konfiguration für Stiebel Eltron WPL 25AC                          #
#  Basierend auf: OneESP32ToRuleThemAll                                       #
#                                                                              #
#  Gerät: heatingpump-esp                                                      #
#  IP: 192.168.178.194                                                         #
#  Update: 2025-11-07                                                          #
#                                                                              #
################################################################################

esphome:
  name: heatingpump-esp
  friendly_name: "Wärmepumpe WPL 25AC"
  comment: "Stiebel Eltron WPL 25AC über CAN-Bus"
  
  # C++17 Support für moderne Features (wichtig für Custom Components)
  platformio_options:
    build_flags:
      - "-std=gnu++17"
      - "-DWPL25AC"  # Define für WPL 25AC spezifischen Code
    build_unflags:
      - "-std=gnu++11"
      - "-fno-rtti"

################################################################################
#  Hardware-Plattform: ESP32
################################################################################
esp32:
  board: esp32dev
  framework:
    type: arduino
    # Optional: Version festlegen für Reproduzierbarkeit
    # version: 2.0.14

################################################################################
#  Logging - Detaillierte Ausgaben für Debugging
################################################################################
logger:
  level: INFO  # Für Produktion: INFO, für Debug: DEBUG
  baud_rate: 115200
  # Spezifische Log-Level für Komponenten
  logs:
    sensor: INFO
    canbus: INFO  # CAN-Bus Traffic detailliert loggen
    binary_sensor: INFO
    climate: INFO

################################################################################
#  Home Assistant API mit Verschlüsselung
################################################################################
api:
  encryption:
    key: !secret api_encryption_key
  # Reboot-Safe-Mode nach 15min ohne HA-Verbindung deaktivieren
  # reboot_timeout: 0s
  
  # Services für erweiterte Steuerung
  services:
    # Manuelles Senden eines CAN-Befehls (für Tests)
    - service: send_can_command
      variables:
        can_id: int
        data: int[]
      then:
        - lambda: |-
            ESP_LOGI("API", "Manueller CAN-Befehl: ID=0x%04X", can_id);
            // TODO: Implementierung mit sendData()

################################################################################
#  OTA Updates (Over-The-Air)
################################################################################
ota:
  - platform: esphome
    password: !secret ota_password

# Safe Mode Component (optional, aber empfohlen)
safe_mode:
  # Aktiviert sich automatisch nach fehlgeschlagenen Updates
  # Nach 10 Minuten im Safe Mode kann erneut geflasht werden
  
################################################################################
#  WLAN Konfiguration
################################################################################
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  
  # Feste IP-Adresse (bereits konfiguriert)
  manual_ip:
    static_ip: 192.168.178.194
    gateway: 192.168.178.1
    dns1: 192.168.178.25
    subnet: 255.255.255.0
  
  # Hostname für mDNS
  use_address: heatingpump.local
  
  # Power-Save deaktivieren für stabilere Verbindung
  power_save_mode: none
  
  # Schnellere Reconnects
  fast_connect: true
  
  # Fallback Hotspot bei WLAN-Problemen
  ap:
    ssid: "Heatingpump Fallback"
    password: !secret ap_fallback_password  # Besser in secrets.yaml

# Captive Portal für Fallback-Konfiguration
captive_portal:

################################################################################
#  Web Server für Diagnose und lokalen Zugriff
################################################################################
web_server:
  port: 80
  version: 3  # Neue Version mit besserer UI
  # Optional: Authentifizierung aktivieren
  # auth:
  #   username: admin
  #   password: !secret web_server_password
  local: true  # Nur im lokalen Netzwerk erreichbar

################################################################################
#  Zeit-Synchronisation mit Home Assistant
################################################################################
time:
  - platform: homeassistant
    id: homeassistant_time
    timezone: Europe/Berlin
    on_time_sync:
      then:
        - logger.log: "Zeit mit Home Assistant synchronisiert"
  - platform: sntp
    id: sntp_time
    timezone: Europe/Berlin
    servers:
      - 192.168.178.1  # Dein Gateway
      - pool.ntp.org        

################################################################################
#  Substitutions - Wiederverwendbare Werte
################################################################################
substitutions:
  # Update-Intervalle für verschiedene Sensor-Typen
  interval_very_fast: "15s"    # Kritische Werte (Temperaturen)
  interval_fast: "30s"          # Wichtige Werte
  interval_medium: "60s"        # Standard-Werte
  interval_slow: "5min"         # Selten ändernde Werte
  interval_very_slow: "15min"   # Statistiken
  interval_once_in_a_while: "1h"  # Sehr selten

  # Home Assistant Entitäten für Raumtemperatur/-feuchte
  entity_room_temperature: "sensor.durchschnittstemperatur"
  entity_humidity: "sensor.durchschnitt_luftfeuchtigkeit_haus"
  
  # Optional: Weitere Entitäten
  # entity_room_temperature_night: "sensor.durchschnittstemperatur_nacht"
  # entity_outdoor_temp: "sensor.aussentemperatur"
  
  # Device-spezifische Werte
  device_name: "heatingpump-esp"
  friendly_name: "Wärmepumpe"

################################################################################
#  SPI Konfiguration für MCP2515 CAN-Transceiver
################################################################################
spi:
  id: McpSpi
  # SPI Pins (bereits korrekt konfiguriert)
  clk_pin: GPIO26   # Clock
  mosi_pin: GPIO27  # Master Out Slave In
  miso_pin: GPIO14  # Master In Slave Out
  # Optional: Frequenz anpassen falls nötig
  # frequency: 10MHz

################################################################################
#  Status-LED (Optional - zur visuellen Kontrolle)
################################################################################
# Onboard-LED als Status-Indikator
status_led:
  pin:
    number: GPIO2
    inverted: true

################################################################################
#  Buttons - Steuerungselemente
################################################################################
button:
  # Neustart-Button
  - platform: restart
    name: "ESP32 Neustart"
    id: restart_button
    icon: "mdi:restart"
    entity_category: diagnostic

  # Safe-Mode Button (bei Problemen)
  - platform: safe_mode
    name: "ESP32 Safe Mode"
    id: safe_mode_button
    icon: "mdi:shield-check"
    entity_category: diagnostic

  # Factory Reset (alle Einstellungen zurücksetzen)
  - platform: factory_reset
    name: "ESP32 Factory Reset"
    id: factory_reset_button
    icon: "mdi:backup-restore"
    entity_category: diagnostic
    disabled_by_default: true  # Sicherheit

################################################################################
#  Binary Sensor - System-Status
################################################################################
binary_sensor:
  # WLAN-Verbindungsstatus
  - platform: status
    name: "ESP32 Status"
    id: esp32_status
    entity_category: diagnostic

################################################################################
#  Sensor - System-Informationen
################################################################################
sensor:
  # WLAN Signal-Stärke
  - platform: wifi_signal
    name: "WLAN Signal"
    id: wifi_signal_strength
    update_interval: 60s
    entity_category: diagnostic
    filters:
      - sliding_window_moving_average:
          window_size: 5
          send_every: 5

  # Uptime (Laufzeit seit letztem Neustart)
  - platform: uptime
    name: "ESP32 Uptime"
    id: esp32_uptime
    update_interval: 60s
    entity_category: diagnostic
    filters:
      - lambda: return x / 3600.0;  # Sekunden → Stunden
    unit_of_measurement: "h"
    accuracy_decimals: 1

  # Freier Heap-Speicher (RAM)
  - platform: template
    name: "ESP32 Free Heap"
    id: esp32_free_heap
    lambda: return ESP.getFreeHeap();
    unit_of_measurement: "bytes"
    update_interval: 60s
    entity_category: diagnostic
    accuracy_decimals: 0

################################################################################
#  Text Sensor - System-Informationen
################################################################################
text_sensor:
  # ESPHome Version
  - platform: version
    name: "ESPHome Version"
    id: esphome_version
    entity_category: diagnostic

  # WLAN Info
  - platform: wifi_info
    ip_address:
      name: "IP Adresse"
      id: wifi_ip
      entity_category: diagnostic
    ssid:
      name: "WLAN SSID"
      id: wifi_ssid_connected
      entity_category: diagnostic
    mac_address:
      name: "MAC Adresse"
      id: wifi_mac
      entity_category: diagnostic

################################################################################
#  Packages - Modulare Integration
################################################################################
# Hier werden die WPL 25AC spezifischen Module eingebunden
packages:
  # Hauptmodul für WPL 25AC CAN-Bus Integration
  wp25ac: !include OneESP32ToRuleWP25AC/yaml/wp25ac.yaml
  
  # Optional: Weitere Module können hier hinzugefügt werden
  # common: !include OneESP32ToRuleWP25AC/yaml/common.yaml
  # sensors: !include OneESP32ToRuleWP25AC/yaml/sensors.yaml

################################################################################
#  Globale Variablen (falls nicht in Packages definiert)
################################################################################
# Diese können auch in den Package-Dateien definiert sein
# globals:
#   - id: g_last_can_error
#     type: std::string
#     restore_value: false
#     initial_value: '""'

################################################################################
#  Intervalle für wiederkehrende Aufgaben
################################################################################
# Nur falls NICHT in wp25ac.yaml definiert
# interval:
#   - interval: 10s
#     then:
#       - logger.log: "Heartbeat: System läuft"

################################################################################
#  KOMMENTARE & HINWEISE
################################################################################
#
# 1. MIGRATION VON DEINER ALTEN KONFIGURATION:
#    ✅ Alle Pins übernommen (GPIO26, 27, 14)
#    ✅ IP-Adresse beibehalten (192.168.178.194)
#    ✅ Intervalle übernommen
#    ✅ HA-Entitäten referenziert
#    ✅ Package-Struktur erweitert
#
# 2. NEUE FEATURES HINZUGEFÜGT:
#    - Status-LED zur visuellen Kontrolle
#    - System-Monitoring (Uptime, RAM, WLAN)
#    - Safe-Mode & Factory-Reset Buttons
#    - Web Server v3 mit besserer UI
#    - API Services für manuelle CAN-Befehle
#    - Power-Save deaktiviert für Stabilität
#
# 3. NÄCHSTE SCHRITTE:
#    a) secrets.yaml aktualisieren:
#       - ap_fallback_password hinzufügen
#    b) OneESP32ToRuleWP25AC/yaml/wp25ac.yaml prüfen
#    c) CAN-Register anpassen (siehe wp25ac.yaml)
#    d) Testen mit: esphome run heatingpump-esp.yaml
#
# 4. DEBUGGING:
#    - Logs anzeigen: esphome logs heatingpump-esp.yaml
#    - Web Interface: http://192.168.178.194
#    - Home Assistant: Geräte & Dienste → ESPHome
#
# 5. SICHERHEIT:
#    ⚠️ Factory-Reset ist standardmäßig deaktiviert
#    ⚠️ Web-Server-Auth aktuell deaktiviert (optional aktivieren)
#    ⚠️ api_encryption_key NIEMALS teilen!
#
################################################################################