# WPL 25AC Passiv-Monitoring
# Version: 3.0 - Nur Empfangen, keine Requests
# Ziel: Alle Bus-Nachrichten mitschneiden ohne aktiv abzufragen

# WICHTIG: Dieses YAML sendet KEINE Requests!
# Es hört nur passiv mit und loggt alles was der Bus sendet.

esphome:
  on_boot:
    - priority: -100
      then:
        - lambda: |-
            ESP_LOGI("PASSIVE", "==============================================");
            ESP_LOGI("PASSIVE", "WPL 25AC Passiv-Monitoring gestartet");
            ESP_LOGI("PASSIVE", "Lausche auf CAN-Bus ohne Requests zu senden");
            ESP_LOGI("PASSIVE", "==============================================");
            ESP_LOGI("PASSIVE", "");
            ESP_LOGI("PASSIVE", "ZIEL: Finde folgende WPM3-Werte:");
            ESP_LOGI("PASSIVE", "  - Verdichter-Starts: 7928");
            ESP_LOGI("PASSIVE", "  - Fortlufttemperatur: 10.3°C (Raw: ~103)");
            ESP_LOGI("PASSIVE", "  - Niederdruck: 10.98 bar");
            ESP_LOGI("PASSIVE", "  - Mitteldruck: 11.00 bar");
            ESP_LOGI("PASSIVE", "  - Hochdruck: 21.41 bar");
            ESP_LOGI("PASSIVE", "  - Abtau-Starts: 600");
            ESP_LOGI("PASSIVE", "  - Spannung Inverter: 417V");
            ESP_LOGI("PASSIVE", "");
            ESP_LOGI("PASSIVE", "Sammle 10 Minuten Daten...");

# Debug-Sensoren für interessante Werte
sensor:
  - platform: template
    name: "DEBUG - Wert um 7928"
    id: debug_7928
    internal: true
    
  - platform: template
    name: "DEBUG - Wert um 103"
    id: debug_103
    internal: true
    
  - platform: template
    name: "DEBUG - Wert um 600"
    id: debug_600
    internal: true

# Zyklisches Log alle 60 Sekunden (nur Info, keine Requests!)
interval:
  - interval: 60s
    then:
      - lambda: |-
          ESP_LOGI("PASSIVE", "--- Monitoring läuft seit %d Sekunden ---", millis()/1000);

# HINWEISE FÜR DIE LOG-ANALYSE:
# 
# Nach 10 Minuten Log, suche nach:
# 
# 1. Verdichter-Starts (7928):
#    grep "raw value" passive_log.txt | awk '$NF > 7920 && $NF < 7935 {print}'
# 
# 2. Fortlufttemp (103):
#    grep "raw value" passive_log.txt | awk '$NF > 101 && $NF < 105 {print}'
# 
# 3. Abtau-Starts (600):
#    grep "raw value" passive_log.txt | awk '$NF > 595 && $NF < 605 {print}'
# 
# 4. Niederdruck (1098 wenn ÷100):
#    grep "raw value" passive_log.txt | awk '$NF > 1095 && $NF < 1102 {print}'
# 
# 5. Hochdruck (2141 wenn ÷100):
#    grep "raw value" passive_log.txt | awk '$NF > 2135 && $NF < 2145 {print}'
# 
# 6. Spannung (417 oder 4170):
#    grep "raw value" passive_log.txt | awk '$NF == 417 || ($NF > 4165 && $NF < 4175) {print}'
#
# 7. Alle Properties mit Häufigkeit:
#    grep "for property" passive_log.txt | \
#      awk -F'property ' '{print $2}' | \
#      awk '{print $1}' | \
#      sort | uniq -c | sort -rn > passive_properties.txt