# ============================================================
# WPL 25AC FINALE PRODUKTIONS-KONFIGURATION
# Version: 2.0 FINAL
# Datum: 2025-11-09
# ============================================================
#
# Enthält nur getestete, funktionierende Sensoren
# KEIN Debug-Logging
# Bereit für Home Assistant Integration
#
# ============================================================

packages:
  COMMON: !include { file: common.yaml}
  BASE:   !include { file: wp_base.yaml}

  # ========================================
  # TEMPERATUREN (8 Sensoren)
  # ========================================
  
  HILFSKESSELSOLL:     !include { file: wp_temperature.yaml, vars: { property: "HILFSKESSELSOLL", target: "Heizmodul", update_interval: "never" }}
  HKISTTEMP:           !include { file: wp_temperature.yaml, vars: { property: "HKISTTEMP", target: "Heizmodul" }}
  WPVORLAUFIST:        !include { file: wp_temperature.yaml, vars: { property: "WPVORLAUFIST", target: "Heizmodul" }}
  OELSUMPFTEMP:        !include { file: wp_temperature.yaml, vars: { property: "OELSUMPFTEMP", target: "Manager", interval: $interval_medium }}
  
 
# ========================================
# SENSOREN (5 zusätzliche)
# ========================================

sensor:
  # === LAUFZEITEN ===
  
  - platform: template
    name: "Laufzeit Verdichter Heizen"
    id: lz_verd_heizen
    unit_of_measurement: "h"
    icon: "mdi:timer"
    accuracy_decimals: 0
    state_class: "total_increasing"
    device_class: "duration"
  
  - platform: template
    name: "Laufzeit Verdichter Warmwasser"
    id: lz_verd_ww
    unit_of_measurement: "h"
    icon: "mdi:timer"
    accuracy_decimals: 0
    state_class: "total_increasing"
    device_class: "duration"
  
  # === DRÜCKE (Multi-Druck-Sensor) ===
  
  - platform: template
    name: "Niederdruck"
    id: niederdruck
    unit_of_measurement: "bar"
    device_class: "pressure"
    state_class: "measurement"
    accuracy_decimals: 2
    icon: "mdi:gauge-low"
    
  - platform: template
    name: "Mitteldruck"
    id: mitteldruck
    unit_of_measurement: "bar"
    device_class: "pressure"
    state_class: "measurement"
    accuracy_decimals: 2
    icon: "mdi:gauge"
    
  - platform: template
    name: "Hochdruck"
    id: hochdruck
    unit_of_measurement: "bar"
    device_class: "pressure"
    state_class: "measurement"
    accuracy_decimals: 2
    icon: "mdi:gauge-high"

# ========================================
# INITIALISIERUNG
# ========================================

esphome:
  on_boot:
    priority: -100
    then:
      - lambda: |-
          // === LAUFZEITEN ===
          
          CallbackHandler::instance().addCallback(
            std::make_pair(Manager, Property::kLZ_VERD_1_HEIZBETRIEB),
            [](const SimpleVariant& value) {
              id(lz_verd_heizen).publish_state(value.get<float>());
            }
          );
          
          CallbackHandler::instance().addCallback(
            std::make_pair(Manager, Property::kLZ_VERD_1_WW_BETRIEB),
            [](const SimpleVariant& value) {
              id(lz_verd_ww).publish_state(value.get<float>());
            }
          );
          
          // === MULTI-DRUCK-SENSOR ===
          
          CallbackHandler::instance().addCallback(
            std::make_pair(Manager, Property::kDRUCK_MULTI),
            [](const SimpleVariant& value) {
              float raw = value.get<float>();
              
              // Ignoriere ungültige Werte
              if (raw == 0 || raw == 32768) {
                return;
              }
              
              // Skalierung: Raw ÷ 100 = bar
              float bar = raw / 100.0;
              
              // Klassifiziere nach Druckbereich
              if (bar < 12.0) {
                // Niederdruck/Mitteldruck
                if (bar < 11.5) {
                  id(niederdruck).publish_state(bar);
                } else {
                  id(mitteldruck).publish_state(bar);
                }
              } else if (bar > 18.0) {
                // Hochdruck
                id(hochdruck).publish_state(bar);
              }
            }
          );

# ========================================
# ZYKLISCHE ABFRAGEN
# ========================================

interval:
  # Laufzeiten alle 5 Minuten
  - interval: 300s
    then:
      - lambda: |-
          queueRequest(Manager, Property::kLZ_VERD_1_HEIZBETRIEB);
          queueRequest(Manager, Property::kLZ_VERD_1_WW_BETRIEB);
  
  # Drücke alle 10 Sekunden
  - interval: 10s
    then:
      - lambda: |-
          queueRequest(Manager, Property::kDRUCK_MULTI);

# ============================================================
# DOKUMENTATION
# ============================================================
#
# VERFÜGBARE SENSOREN (17):
#
# TEMPERATUREN (7):
# - sensor.aussentemp              (Außentemperatur)
# - sensor.speicheristtemp         (Warmwasser-Ist)
# - sensor.wpvorlaufist            (Vorlauf-Ist)
# - sensor.ruecklaufisttemp        (Rücklauf-Ist)
# - sensor.hilfskesselsoll         (Hilfskesselsoll)
# - sensor.hkisttemp               (Heizkreis-Ist)
# - sensor.oelsumpftemp            (Ölsumpftemperatur)
#
# DRÜCKE (3):
# - sensor.niederdruck             (8-11.5 bar)
# - sensor.mitteldruck             (11.5-12 bar)
# - sensor.hochdruck               (18-25 bar)
#
# LAUFZEITEN (2):
# - sensor.laufzeit_verdichter_heizen      (Stunden)
# - sensor.laufzeit_verdichter_warmwasser  (Stunden)
#
# ENERGIE (4):
# - sensor.waermeertrag_heiz_summe_mwh
# - sensor.waermeertrag_ww_summe_mwh
# - sensor.waermeertrag_2we_heiz_summe_mwh
# - sensor.waermeertrag_2we_ww_summe_mwh
#
# ZÄHLER (1):
# - sensor.verdichter_starts
#
# PLUS: Binary-Sensoren aus wp_base.yaml
#
# ============================================================