# OneESP32ToRuleWP25AC/yaml/wp25ac.yaml
# esphome:
#   name: dummy
#   platformio_options:
#     build_flags:
#       - "-DWP25AC"

packages:
  COMMON: !include { file: common.yaml}
  BASE:   !include { file: wp_base.yaml}
  TEST:   !include { file: wp25ac_test.yaml}
  
  # ========================================
  # HEIZMODUL-TEMPERATUREN (0x500)
  # ========================================
  HILFSKESSELSOLL:                !include { file: wp_temperature.yaml, vars: { property: "HILFSKESSELSOLL", target: "Heizmodul", update_interval: "never" }}
  HKISTTEMP_HEIZMODUL:            !include { file: wp_temperature.yaml, vars: { property: "HKISTTEMP", target: "Heizmodul" }}
  WPVORLAUFIST:                   !include { file: wp_temperature.yaml, vars: { property: "WPVORLAUFIST", target: "Heizmodul" }}
  OELSUMPFTEMP:  !include { file: wp_temperature.yaml, vars: { property: "OELSUMPFTEMP", target: "Manager" }}
  FORTLUFTTEMP:  !include { file: wp_temperature.yaml, vars: { property: "FORTLUFTTEMP", target: "Kessel" }}
    
   
  # ========================================
  # KESSEL-TEMPERATUREN (0x180)
  # Hinweis: Kessel sendet oft 0, Response (0x100) hat echte Werte!
  # ========================================
  # VORLAUFISTTEMP:                 !include { file: wp_temperature.yaml, vars: { property: "VORLAUFISTTEMP", target: "Kessel" }}
  # RAUMISTTEMP:                    !include { file: wp_temperature.yaml, vars: { property: "RAUMISTTEMP", target: "Kessel" }}


# ========================================
# ZUSÄTZLICHE SENSOREN (Custom)
# ========================================
sensor:
  # Software-Version der Steuerung
  - platform: template
    name: "WP Software Version"
    id: wp_software_version
    icon: "mdi:information"
    accuracy_decimals: 2
    update_interval: never
    lambda: |-
        queueRequest(Manager, Property::kSOFTWARE_NUMMER);
        return {};

  # Verdichter-Temperatur (alternative Darstellung)
  - platform: template
    name: "Verdichter Status"
    id: verdichter_status
    unit_of_measurement: "°C"
    device_class: "temperature"
    accuracy_decimals: 1
    update_interval: $interval_medium
    lambda: |-
        queueRequest(Manager, Property::kVERDICHTER);
        return {};

  - platform: template
    name: "Verdichter Starts (Test)"
    id: verdichter_starts_test
    icon: "mdi:counter"
    update_interval: 60s
    lambda: |-
        queueRequest(Kessel, Property::kVERDICHTER_STARTS_NEU);
        return {};        

esphome:
  on_boot:
    priority: -100
    then:
      - lambda: |-
          // Software-Version Callback
          CallbackHandler::instance().addCallback(std::make_pair(Manager,Property::kSOFTWARE_NUMMER),[](const SimpleVariant& value){
              id(wp_software_version).publish_state(value.get<float>());
          });
          queueRequest(Manager, Property::kSOFTWARE_NUMMER);
          
          // Verdichter Callback
          CallbackHandler::instance().addCallback(std::make_pair(Manager,Property::kVERDICHTER),[](const SimpleVariant& value){
              id(verdichter_status).publish_state(value.get<float>());
          });
          queueRequest(Manager, Property::kVERDICHTER);
          
          CallbackHandler::instance().addCallback(
            std::make_pair(Kessel, Property::kVERDICHTER_STARTS_NEU),
            [](const SimpleVariant& value) {
              id(verdichter_starts_test).publish_state(value.get<float>());
              ESP_LOGI("TEST", "VERDICHTER_STARTS_NEU = %.0f", value.get<float>());
            }
          );
# ========================================
# NOTIZEN & TODO
# ========================================
# 
# FUNKTIONIERENDE REGISTER:
# ✅ AUSSENTEMP (0x000C) via Response (0x100)
# ✅ SPEICHERISTTEMP (0x000E) via Response (0x100)  
# ✅ RUECKLAUFISTTEMP (0x0016) via Response (0x100)
# ✅ HILFSKESSELSOLL (0x01D7) via Heizmodul (0x500)
# ✅ HKISTTEMP (0x02CA) via Heizmodul (0x500)
# ✅ VERDICHTER (0x07A8) via Manager (0x480)
# ✅ SOFTWARE_NUMMER (0x0199) via Manager (0x480)
#
# NOCH ZU TESTEN:
# ⏳ VORLAUFSOLLTEMP (0x0004) - Sollwert für Vorlauf
# ⏳ PUFFERISTTEMP (0x0078) - Puffer-Ist-Temperatur
# ⏳ PUFFERSOLLTEMP (0x01D5) - Puffer-Soll-Temperatur
# ⏳ RAUMSOLLTEMP_I (0x0005) - Raumsolltemperatur HK1
# ⏳ RAUMSOLLTEMP_II (0x0006) - Raumsolltemperatur HK2
#
# BEKANNTE PROBLEME:
# ⚠️ HKISTTEMP von 0x500 liefert 2 verschiedene Werte (310 & 375)
#    → Vermutlich HK1 und HK2, aber Unterscheidung unklar
#    → Workaround: Beide tracken, dann per HA-Automatisierung zuordnen
#
# ⚠️ Kessel (0x180) sendet oft Wert 0 (ungültig)
#    → Response (0x100) hat die echten Werte!
#    → Target immer auf "Response" setzen
#
# ⚠️ ESPClient (0x700) sendet 32768 (0x8000 = Fehlerwert)
#    → Das sind unsere eigenen Requests ohne Antwort
#    → Ignorieren oder Timeout erhöhen
#
# NÄCHSTE SCHRITTE:
# 1. 5-Minuten-Log sammeln für vollständige HK-Analyse
# 2. VORLAUFSOLLTEMP-Register testen
# 3. Puffer-Temperaturen einbinden
# 4. HK1/HK2-Unterscheidung final klären
# 5. Status-Bits (WAERMEPUMPEN_STATUS) implementieren
#
# ========================================
  
  
  

  # QUELLE_IST:                     !include { file: wp_temperature.yaml, vars: { property: "QUELLE_IST" }}
  # HILFSKESSELSOLL:                !include { file: wp_temperature.yaml, vars: { property: "HILFSKESSELSOLL", update_interval: "never" }}
  # HKISTTEMP:                      !include { file: wp_temperature.yaml, vars: { property: "HKISTTEMP" }}
  # PUFFERISTTEMP:                  !include { file: wp_temperature.yaml, vars: { property: "PUFFERISTTEMP" }}
  # PUFFERSOLLTEMP:                 !include { file: wp_temperature.yaml, vars: { property: "PUFFERSOLLTEMP" }}
#  DRUCK_HEIZKREIS:                !include { file: wp_generic.yaml, vars: { property: "DRUCK_HEIZKREIS", interval: "never", unit: "bar"  , icon: "mdi:water-pressure", accuracy_decimals: "1" }}
#  QUELLENDRUCK:                   !include { file: wp_generic.yaml, vars: { property: "QUELLENDRUCK"   , interval: "never", unit: "bar"  , icon: "mdi:water-pressure", accuracy_decimals: "1" }}
#  SOMMERBETRIEB_TEMP:             !include { file: wp_number.yaml, vars:  { property: "SOMMERBETRIEB_TEMP", icon: "mdi:sun-thermometer", min: "15.0", max: "25.0", step: "1.0", unit: "°C"  }}  